### ISSUE TITLE
Let cruftbot manage the boilerplate for you!


### ISSUE THREAD

**Issue by 0cruft** [0cry/zwuvqgftdihm#1]
Thank you for choosing cruftbot to start your next project.

To create new project from template repository leave a comment like this:

    @{{ user }} create https://github.com/audreyfeldroy/cookiecutter-pypackage

    ```yml
    full_name: John Doe
    email: johndoe@example.com
    github_username: johndoe
    project_name: My Awesome Python Project
    use_pypi_deployment_with_travis: n
    ```

Generated project would be sent to this repository in pull request.

When template repository would receive changes, it would be mirrored into this project in new pull requests with respect to the values used to create project.
